"""add users table and role-based attribution

Revision ID: 4dba9171375c
Revises: 891b3b43f1db
Create Date: 2026-09-21 06:37:56.980931

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4dba9171375c"
down_revision: str | None = "891b3b43f1db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Enum("ADMIN", "LEAD", "DEVELOPER", name="userrole"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("ix_users_tenant", "users", ["tenant_id"], unique=False)
    op.add_column("agent_tasks", sa.Column("user_id", sa.UUID(), nullable=True))
    op.create_foreign_key("fk_agent_tasks_user_id", "agent_tasks", "users", ["user_id"], ["id"], ondelete="SET NULL")
    op.add_column("api_keys", sa.Column("user_id", sa.UUID(), nullable=True))
    op.create_foreign_key("fk_api_keys_user_id", "api_keys", "users", ["user_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_api_keys_user_id", "api_keys", type_="foreignkey")
    op.drop_column("api_keys", "user_id")
    op.drop_constraint("fk_agent_tasks_user_id", "agent_tasks", type_="foreignkey")
    op.drop_column("agent_tasks", "user_id")
    op.drop_index("ix_users_tenant", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###

    # Native-Postgres-enum cleanup (see 891b3b43f1db's downgrade for the same
    # gotcha): the table drop above doesn't drop the ENUM type itself, so a
    # downgrade followed by a re-upgrade would otherwise fail with "type
    # userrole already exists".
    bind = op.get_bind()
    sa.Enum(name="userrole").drop(bind, checkfirst=True)
