"""add model adapters table

Revision ID: 52e74272c1a4
Revises: 4dba9171375c
Create Date: 2026-09-21 08:38:23.288980

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "52e74272c1a4"
down_revision: str | None = "4dba9171375c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_adapters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("base_model_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("benchmark_run_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.Enum("CANDIDATE", "PROMOTED", "RETIRED", name="adapterstatus"), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["finetune_jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_model_adapters_tenant_base_model", "model_adapters", ["tenant_id", "base_model_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_model_adapters_tenant_base_model", table_name="model_adapters")
    op.drop_table("model_adapters")
    # ### end Alembic commands ###

    # Native-Postgres-enum cleanup (same gotcha as every earlier migration
    # that added one — see 891b3b43f1db's downgrade): the table drop above
    # doesn't drop the ENUM type itself.
    bind = op.get_bind()
    sa.Enum(name="adapterstatus").drop(bind, checkfirst=True)
