"""add agent memory and task feedback tables

Revision ID: 891b3b43f1db
Revises: ffafa94a7062
Create Date: 2026-09-20 23:57:27.232597

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "891b3b43f1db"
down_revision: str | None = "ffafa94a7062"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_memories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("repository", sa.String(length=1024), nullable=True),
        sa.Column("scope", sa.Enum("REPO", "TENANT", name="memoryscope"), nullable=False),
        sa.Column("kind", sa.Enum("CONVENTION", "PREFERENCE", "FACT", "AVOID", name="memorykind"), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source", sa.Enum("AUTO", "USER", name="memorysource"), nullable=False),
        sa.Column("status", sa.Enum("PROPOSED", "APPROVED", "FORGOTTEN", name="memorystatus"), nullable=False),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("hit_count", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_agent_memories_status", "agent_memories", ["status"], unique=False)
    op.create_index("ix_agent_memories_tenant_repo", "agent_memories", ["tenant_id", "repository"], unique=False)
    op.create_table(
        "task_feedback",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column(
            "verdict", sa.Enum("ACCEPTED", "REJECTED", "MERGED", "REVERTED", name="feedbackverdict"), nullable=False
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["task_id"], ["agent_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_task_feedback_task", "task_feedback", ["task_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_task_feedback_task", table_name="task_feedback")
    op.drop_table("task_feedback")
    op.drop_index("ix_agent_memories_tenant_repo", table_name="agent_memories")
    op.drop_index("ix_agent_memories_status", table_name="agent_memories")
    op.drop_table("agent_memories")
    # ### end Alembic commands ###

    # Alembic's autogenerate drops the tables that reference these native
    # Postgres ENUM types but not the types themselves — without this, a
    # downgrade followed by a re-upgrade fails with "type already exists"
    # (same gotcha as the baseline migration's own downgrade).
    bind = op.get_bind()
    sa.Enum(name="feedbackverdict").drop(bind, checkfirst=True)
    sa.Enum(name="memorystatus").drop(bind, checkfirst=True)
    sa.Enum(name="memorysource").drop(bind, checkfirst=True)
    sa.Enum(name="memorykind").drop(bind, checkfirst=True)
    sa.Enum(name="memoryscope").drop(bind, checkfirst=True)
