"""add git workflow columns to agent_tasks

Revision ID: ffafa94a7062
Revises: 50fcc5b3f147
Create Date: 2026-09-20 14:01:44.429318

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ffafa94a7062"
down_revision: str | None = "50fcc5b3f147"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent_tasks", sa.Column("branch_name", sa.String(length=255), nullable=True))
    op.add_column("agent_tasks", sa.Column("commit_sha", sa.String(length=64), nullable=True))
    op.add_column("agent_tasks", sa.Column("pr_url", sa.String(length=1024), nullable=True))
    op.add_column("agent_tasks", sa.Column("pr_number", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_tasks", "pr_number")
    op.drop_column("agent_tasks", "pr_url")
    op.drop_column("agent_tasks", "commit_sha")
    op.drop_column("agent_tasks", "branch_name")
    # ### end Alembic commands ###
