# Copyright 2024-2026 Gaurav Gupta / Keystone
# Licensed under the Apache License, Version 2.0

"""
Keystone — IDE configuration (`keystone ide ...`).

VS Code via the Continue extension: one rendered `config.yaml` that points
Continue's chat/edit/apply roles at Keystone's `coding` model, autocomplete
at the cheaper `coding_fallback`, and Continue's MCP client at Keystone's
memory tools — all through the same OpenAI-compatible gateway and the same
API key OpenCode already uses (`cli/opencode.config.json`).

Field names follow Continue's own config-yaml schema (packages/config-yaml
in continuedev/continue): a model entry is `name`/`provider`/`model`/
`apiBase`/`apiKey`/`roles` (roles ∈ chat, autocomplete, embed, rerank,
edit, apply, summarize, subagent); a remote MCP server is `name`/`type`
(`streamable-http`)/`url`/`requestOptions.headers`. The rendering is a pure
function so tests can parse its output; the CLI only writes it to a file.
"""

from __future__ import annotations

from dataclasses import dataclass

CONTINUE_SCHEMA_VERSION = "v1"


@dataclass(frozen=True)
class ContinueConfigInputs:
    base_url: str  # e.g. https://keystone.example.internal:8080  (no trailing /v1)
    api_key: str
    coding_model: str = "coding"  # the role names the gateway routes (src/inference/model_router.py)
    autocomplete_model: str = "coding_fallback"
    context_length: int = 131_072
    max_tokens: int = 16_384
    ca_bundle_path: str | None = None  # the internal CA (pki/) for an air-gapped deployment's TLS


def _yaml_str(value: str) -> str:
    """Double-quoted YAML scalar — keys and URLs never need more than this."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_continue_config(inputs: ContinueConfigInputs) -> str:
    base = inputs.base_url.rstrip("/")
    api_base = f"{base}/v1"
    mcp_url = f"{base}/v1/keystone/mcp"
    request_options = ""
    if inputs.ca_bundle_path:
        request_options = f"    requestOptions:\n      caBundlePath: {_yaml_str(inputs.ca_bundle_path)}\n"
    lines = [
        "# Continue (VS Code) configuration for Keystone — generated by `keystone ide continue-config`.",
        "# Chat/edit/apply use the coding model, autocomplete the cheaper fallback; the MCP server exposes",
        "# Keystone's memory tools (memory_search / memory_add) to Continue's agent. Same gateway and API key",
        "# as cli/opencode.config.json. Place at ~/.continue/config.yaml (or add it as a local assistant).",
        "name: Keystone",
        "version: 0.0.1",
        f"schema: {CONTINUE_SCHEMA_VERSION}",
        "",
        "models:",
        "  - name: Keystone coding",
        "    provider: openai",
        f"    model: {_yaml_str(inputs.coding_model)}",
        f"    apiBase: {_yaml_str(api_base)}",
        f"    apiKey: {_yaml_str(inputs.api_key)}",
        "    roles: [chat, edit, apply, summarize]",
        "    capabilities: [tool_use]",
        "    defaultCompletionOptions:",
        f"      contextLength: {inputs.context_length}",
        f"      maxTokens: {inputs.max_tokens}",
        "      temperature: 0.2",
        request_options.rstrip("\n") if request_options else None,
        "  - name: Keystone autocomplete",
        "    provider: openai",
        f"    model: {_yaml_str(inputs.autocomplete_model)}",
        f"    apiBase: {_yaml_str(api_base)}",
        f"    apiKey: {_yaml_str(inputs.api_key)}",
        "    roles: [autocomplete]",
        "    defaultCompletionOptions:",
        f"      contextLength: {inputs.context_length}",
        "      maxTokens: 256",
        "      temperature: 0.0",
        request_options.rstrip("\n") if request_options else None,
        "",
        "mcpServers:",
        "  - name: Keystone memory",
        "    type: streamable-http",
        f"    url: {_yaml_str(mcp_url)}",
        "    requestOptions:",
        "      headers:",
        f"        Authorization: {_yaml_str('Bearer ' + inputs.api_key)}",
        (f"      caBundlePath: {_yaml_str(inputs.ca_bundle_path)}" if inputs.ca_bundle_path else None),
        "",
        "rules:",
        "  - name: Keystone conventions",
        "    rule: >-",
        "      Before editing, search Keystone memory (memory_search) for this repository's conventions and",
        "      things to avoid; after a task the user accepts, offer to record a new convention with memory_add.",
        "",
    ]
    return "\n".join(line for line in lines if line is not None)
