#!/usr/bin/env python3
# Copyright 2024-2026 Gaurav Gupta / Keystone
# Licensed under the Apache License, Version 2.0

"""
Generate docs/reference/cli.md from the `keystone` CLI's own --help output (every command and subcommand),
and docs/reference/api.md from the application's OpenAPI document — so both references are what the code
does, not what someone remembered.

    python scripts/gen_cli_reference.py            # (re)write both pages
    python scripts/gen_cli_reference.py --check    # exit 1 if either page is stale (CI)
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

# Deterministic help rendering regardless of the terminal this runs in (a developer's shell, CI): typer's
# rich output reads these before anything is imported, so they must be set here, first.
os.environ["TERMINAL_WIDTH"] = "100"
os.environ["COLUMNS"] = "100"
os.environ["NO_COLOR"] = "1"
os.environ["TERM"] = "dumb"
os.environ["_TYPER_FORCE_DISABLE_TERMINAL"] = "1"

ROOT = Path(__file__).resolve().parent.parent
CLI_OUT = ROOT / "docs" / "reference" / "cli.md"
API_OUT = ROOT / "docs" / "reference" / "api.md"

_ANSI = re.compile(r"\x1b\[[0-9;]*m")


def _plain_group(app):
    """The click command tree with typer's rich rendering disabled — plain click help, whose layout depends
    only on the fixed width above, not on the rich/typer version installed."""
    import click
    import typer.core
    import typer.main

    typer.core.HAS_RICH = False  # typer falls back to click's own formatter when rich is unavailable
    return click, typer.main.get_command(app)


def _help_pages(app) -> list[tuple[list[str], str]]:
    """(command path, help text) for the root and every command and subcommand, in registration order."""
    click, root = _plain_group(app)
    pages: list[tuple[list[str], str]] = []

    def visit(cmd, path: list[str], parent_ctx) -> None:
        ctx = click.Context(cmd, info_name=path[-1] if path else "keystone", parent=parent_ctx, terminal_width=100)
        text = _ANSI.sub("", cmd.get_help(ctx))
        pages.append((path, "\n".join(line.rstrip() for line in text.splitlines()).strip() + "\n"))
        for name in getattr(cmd, "commands", {}):
            visit(cmd.commands[name], [*path, name], ctx)

    visit(root, [], None)
    return pages


def render_cli() -> str:
    from src.cli.main import app

    parts = [
        "# CLI reference",
        "",
        "Every `keystone` command, from the CLI's own `--help` (generated by `scripts/gen_cli_reference.py`; CI fails "
        "when this page is stale). The CLI is a real HTTP client against a running deployment "
        "(`KEYSTONE_INFERENCE_URL`, `KEYSTONE_API_KEY`; admin commands need `KEYSTONE_ROOT_ADMIN_TOKEN`), except "
        "`init`, `doctor`, `up`/`down`, `bundle` and `deploy`, which work on the machine they run on.",
        "",
    ]
    for path, text in _help_pages(app):
        title = "keystone" if not path else f"keystone {' '.join(path)}"
        parts += [f"## {title}", "", "```text", text.rstrip(), "```", ""]
    return "\n".join(parts)


def render_api() -> str:
    from src.main import create_app

    spec = create_app().openapi()
    parts = [
        "# API reference",
        "",
        "Every HTTP route the application serves, from its OpenAPI document (generated by "
        "`scripts/gen_cli_reference.py`; CI fails when this page is stale). The live, interactive version is at "
        "`/docs` on any deployment. Authentication: `Authorization: Bearer ks-…` (or `x-api-key`) for tenant "
        "routes; the root admin token for `/v1/admin/*`.",
        "",
        "| Method | Path | Summary | Tags |",
        "|---|---|---|---|",
    ]
    for path in sorted(spec.get("paths", {})):
        for method, op in sorted(spec["paths"][path].items()):
            if method.upper() not in ("GET", "POST", "PUT", "PATCH", "DELETE"):
                continue
            summary = (op.get("summary") or (op.get("description") or "").split("\n")[0]).strip().replace("|", "\\|")
            tags = ", ".join(op.get("tags") or [])
            parts.append(f"| `{method.upper()}` | `{path}` | {summary} | {tags} |")
    parts.append("")
    return "\n".join(parts)


def main(argv: list[str]) -> int:
    sys.path.insert(0, str(ROOT))
    os.environ.setdefault("VS_SECRET_KEY", "reference-generation-" + "0" * 43)
    pages = {CLI_OUT: render_cli(), API_OUT: render_api()}
    if "--check" in argv:
        stale = [p for p, content in pages.items() if not p.exists() or p.read_text() != content]
        if stale:
            for p in stale:
                print(f"{p.relative_to(ROOT)} is stale — run: python scripts/gen_cli_reference.py", file=sys.stderr)
            return 1
        print("docs/reference/cli.md and docs/reference/api.md are up to date")
        return 0
    for p, content in pages.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content)
        print(f"wrote {p.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
