#!/usr/bin/env python3
# Copyright 2024-2026 Gaurav Gupta / Keystone
# Licensed under the Apache License, Version 2.0

"""
Generate docs/reference/cli.md from the `keystone` CLI's own --help output (every command and subcommand),
and docs/reference/api.md from the application's OpenAPI document — so both references are what the code
does, not what someone remembered.

    python scripts/gen_cli_reference.py            # (re)write both pages
    python scripts/gen_cli_reference.py --check    # exit 1 if either page is stale (CI)
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CLI_OUT = ROOT / "docs" / "reference" / "cli.md"
API_OUT = ROOT / "docs" / "reference" / "api.md"

_ANSI = re.compile(r"\x1b\[[0-9;]*m")


def _help(app, args: list[str]) -> str:
    from typer.testing import CliRunner

    env = {**os.environ, "TERM": "dumb", "NO_COLOR": "1", "COLUMNS": "100"}
    result = CliRunner().invoke(app, [*args, "--help"], env=env)
    text = _ANSI.sub("", result.output)
    # typer/rich box drawing is fine in a fenced block; strip trailing spaces for stable diffs
    return "\n".join(line.rstrip() for line in text.splitlines()).strip() + "\n"


def _walk(app) -> list[list[str]]:
    """Every command path, depth-first, in registration order."""
    import typer
    from typer.main import get_group

    group = get_group(app)
    paths: list[list[str]] = []

    def visit(cmd, prefix: list[str]) -> None:
        commands = getattr(cmd, "commands", {})
        for name in commands:
            sub = commands[name]
            paths.append([*prefix, name])
            visit(sub, [*prefix, name])

    visit(group, [])
    del typer
    return paths


def render_cli() -> str:
    from src.cli.main import app

    parts = [
        "# CLI reference",
        "",
        "Every `keystone` command, from the CLI's own `--help` (generated by `scripts/gen_cli_reference.py`; CI fails "
        "when this page is stale). The CLI is a real HTTP client against a running deployment "
        "(`KEYSTONE_INFERENCE_URL`, `KEYSTONE_API_KEY`; admin commands need `KEYSTONE_ROOT_ADMIN_TOKEN`), except "
        "`init`, `doctor`, `up`/`down`, `bundle` and `deploy`, which work on the machine they run on.",
        "",
        "## keystone",
        "",
        "```text",
        _help(app, []).rstrip(),
        "```",
        "",
    ]
    for path in _walk(app):
        parts += [f"## keystone {' '.join(path)}", "", "```text", _help(app, path).rstrip(), "```", ""]
    return "\n".join(parts)


def render_api() -> str:
    from src.main import create_app

    spec = create_app().openapi()
    parts = [
        "# API reference",
        "",
        "Every HTTP route the application serves, from its OpenAPI document (generated by "
        "`scripts/gen_cli_reference.py`; CI fails when this page is stale). The live, interactive version is at "
        "`/docs` on any deployment. Authentication: `Authorization: Bearer ks-…` (or `x-api-key`) for tenant "
        "routes; the root admin token for `/v1/admin/*`.",
        "",
        "| Method | Path | Summary | Tags |",
        "|---|---|---|---|",
    ]
    for path in sorted(spec.get("paths", {})):
        for method, op in sorted(spec["paths"][path].items()):
            if method.upper() not in ("GET", "POST", "PUT", "PATCH", "DELETE"):
                continue
            summary = (op.get("summary") or (op.get("description") or "").split("\n")[0]).strip().replace("|", "\\|")
            tags = ", ".join(op.get("tags") or [])
            parts.append(f"| `{method.upper()}` | `{path}` | {summary} | {tags} |")
    parts.append("")
    return "\n".join(parts)


def main(argv: list[str]) -> int:
    sys.path.insert(0, str(ROOT))
    os.environ.setdefault("VS_SECRET_KEY", "reference-generation-" + "0" * 43)
    pages = {CLI_OUT: render_cli(), API_OUT: render_api()}
    if "--check" in argv:
        stale = [p for p, content in pages.items() if not p.exists() or p.read_text() != content]
        if stale:
            for p in stale:
                print(f"{p.relative_to(ROOT)} is stale — run: python scripts/gen_cli_reference.py", file=sys.stderr)
            return 1
        print("docs/reference/cli.md and docs/reference/api.md are up to date")
        return 0
    for p, content in pages.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content)
        print(f"wrote {p.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
