#!/usr/bin/env bash
# Copyright 2024-2026 Gaurav Gupta / Keystone — Apache 2.0
#
# Initializes/unseals the OpenBao instance started by
# `docker compose --profile secrets up -d openbao`, seeds it with the
# secrets Keystone needs (generating strong random values for any not
# already present), and renders .env.generated with those values pulled
# back OUT of OpenBao — proving the read path works, not just the write
# path. `docker compose --env-file .env.generated up` then boots the rest
# of the stack from real OpenBao-sourced secrets instead of hand-typed
# ones in .env.
#
# Unlike OpenBao's `-dev` mode (in-memory, auto-unsealed, root token is a
# fixed string — fine for the live-test in this repo's commit history, not
# for anything durable), this script drives the *real* init/unseal
# lifecycle against the file-backed storage configured in
# docker-compose.yml's `openbao` service, because that's the lifecycle a
# production/client deployment actually has to run.
#
# State (unseal key + root token) is written to openbao/.openbao-init.json
# with 0600 perms — .gitignore already excludes it. Losing that file with
# no other unseal key recorded means the KV data is unrecoverable; this
# script is for dev/test bootstrapping, not a production key-management
# procedure (production should use OpenBao's auto-unseal + a real KMS,
# documented as a TODO in docs/deployment for the client's actual cloud).

set -euo pipefail

BAO_ADDR="${BAO_ADDR:-http://127.0.0.1:8200}"
STATE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/openbao"
STATE_FILE="${STATE_DIR}/.openbao-init.json"
ENV_OUT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/.env.generated"

mkdir -p "${STATE_DIR}"

command -v curl >/dev/null || { echo "curl is required" >&2; exit 1; }
command -v jq >/dev/null || { echo "jq is required (brew install jq / apt-get install jq)" >&2; exit 1; }

echo "==> Waiting for OpenBao at ${BAO_ADDR} ..."
for _ in $(seq 1 30); do
  status="$(curl -s -o /dev/null -w '%{http_code}' "${BAO_ADDR}/v1/sys/health?standbyok=true&uninitcode=200&sealedcode=200" || true)"
  [[ "${status}" =~ ^(200|429|501|503)$ ]] && break
  sleep 2
done

init_status="$(curl -s "${BAO_ADDR}/v1/sys/init" | jq -r '.initialized')"

if [[ "${init_status}" != "true" ]]; then
  echo "==> Initializing OpenBao (1 key share, threshold 1 — dev/test tier only)"
  curl -s --request POST \
    --data '{"secret_shares": 1, "secret_threshold": 1}' \
    "${BAO_ADDR}/v1/sys/init" | tee "${STATE_FILE}" >/dev/null
  chmod 600 "${STATE_FILE}"
else
  echo "==> OpenBao already initialized; reusing ${STATE_FILE}"
  [[ -f "${STATE_FILE}" ]] || { echo "FATAL: initialized but ${STATE_FILE} missing — cannot unseal" >&2; exit 1; }
fi

ROOT_TOKEN="$(jq -r '.root_token' "${STATE_FILE}")"
UNSEAL_KEY="$(jq -r '.keys_base64[0]' "${STATE_FILE}")"

sealed="$(curl -s "${BAO_ADDR}/v1/sys/seal-status" | jq -r '.sealed')"
if [[ "${sealed}" == "true" ]]; then
  echo "==> Unsealing"
  curl -s --request POST --data "{\"key\": \"${UNSEAL_KEY}\"}" "${BAO_ADDR}/v1/sys/unseal" >/dev/null
fi

# KV v2 mount (idempotent — 400 "path is already in use" is fine)
curl -s --header "X-Vault-Token: ${ROOT_TOKEN}" --request POST \
  --data '{"type": "kv", "options": {"version": "2"}}' \
  "${BAO_ADDR}/v1/sys/mounts/secret" >/dev/null 2>&1 || true

_rand() { openssl rand -hex 32; }

_get_or_generate() {
  local path="$1" field="$2"
  local existing
  existing="$(curl -s --header "X-Vault-Token: ${ROOT_TOKEN}" "${BAO_ADDR}/v1/secret/data/${path}" \
    | jq -r ".data.data.${field} // empty")"
  if [[ -n "${existing}" ]]; then
    echo "${existing}"
  else
    _rand
  fi
}

echo "==> Seeding secrets/ (generating any not already present)"
POSTGRES_PASSWORD="$(_get_or_generate keystone/postgres password)"
REDIS_PASSWORD="$(_get_or_generate keystone/redis password)"
QDRANT_API_KEY="$(_get_or_generate keystone/qdrant api_key)"
KEYSTONE_ROOT_ADMIN_TOKEN="$(_get_or_generate keystone/root-admin token)"
VS_SECRET_KEY="$(_get_or_generate keystone/app secret_key)"

_put() { # path field value
  curl -s --header "X-Vault-Token: ${ROOT_TOKEN}" --request POST \
    --data "{\"data\": {\"${2}\": \"${3}\"}}" \
    "${BAO_ADDR}/v1/secret/data/${1}" >/dev/null
}
_put keystone/postgres password "${POSTGRES_PASSWORD}"
_put keystone/redis password "${REDIS_PASSWORD}"
_put keystone/qdrant api_key "${QDRANT_API_KEY}"
_put keystone/root-admin token "${KEYSTONE_ROOT_ADMIN_TOKEN}"
_put keystone/app secret_key "${VS_SECRET_KEY}"

echo "==> Reading secrets back from OpenBao to render ${ENV_OUT}"
{
  echo "# Generated by scripts/openbao_bootstrap.sh — sourced FROM OpenBao, not hand-typed."
  echo "# Regenerate with: ./scripts/openbao_bootstrap.sh"
  echo "POSTGRES_PASSWORD=$(curl -s --header "X-Vault-Token: ${ROOT_TOKEN}" "${BAO_ADDR}/v1/secret/data/keystone/postgres" | jq -r '.data.data.password')"
  echo "REDIS_PASSWORD=$(curl -s --header "X-Vault-Token: ${ROOT_TOKEN}" "${BAO_ADDR}/v1/secret/data/keystone/redis" | jq -r '.data.data.password')"
  echo "QDRANT_API_KEY=$(curl -s --header "X-Vault-Token: ${ROOT_TOKEN}" "${BAO_ADDR}/v1/secret/data/keystone/qdrant" | jq -r '.data.data.api_key')"
  echo "KEYSTONE_ROOT_ADMIN_TOKEN=$(curl -s --header "X-Vault-Token: ${ROOT_TOKEN}" "${BAO_ADDR}/v1/secret/data/keystone/root-admin" | jq -r '.data.data.token')"
  echo "VS_SECRET_KEY=$(curl -s --header "X-Vault-Token: ${ROOT_TOKEN}" "${BAO_ADDR}/v1/secret/data/keystone/app" | jq -r '.data.data.secret_key')"
} > "${ENV_OUT}"
chmod 600 "${ENV_OUT}"

echo "==> Verifying an unauthenticated/garbage-token read is rejected"
rejected_status="$(curl -s -o /dev/null -w '%{http_code}' --header "X-Vault-Token: garbage" "${BAO_ADDR}/v1/secret/data/keystone/postgres")"
if [[ "${rejected_status}" != "403" ]]; then
  echo "FATAL: expected 403 for a bad token, got ${rejected_status}" >&2
  exit 1
fi

echo "==> Done. Root token / unseal key kept in ${STATE_FILE} (0600, gitignored)."
echo "==> Bring up the rest of the stack with:"
echo "    docker compose --env-file .env.generated up -d app worker sandbox-daemon postgres redis qdrant temporal temporal-ui nginx"
